[build]
  command = "npm run build"
  publish = "dist"
  functions = ".output/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  external_node_modules = ["h3"]

[build.environment]
  NODE_VERSION = "20.15.0"